### ISSUE TITLE
images?

### ISSUE THREAD

**Issue by treasuretron** [qypea/ssb-client-cli#6] opened 2019-06-18 03:50 UTC
Running ssb-client publish post --help suggests that there's not currently a way to post images, is this correct? Any way this might be coming up or easily hacked in? Thanks!!!

**Comment by qypea** [comment] 2019-06-18 12:07
Closing as a duplicate of #2
To support adding images we would need to support blob.add I believe. That would take care of it for us

**Closed as completed by qypea** 2019-06-18 12:07 UTC
Labels: duplicate
